#!/bin/sh

set -e

case "$(dpkg --print-architecture)" in
	amd64)
		_LINUX_FLAVOURS="amd64"
		_SOURCE="false"
		;;

	i386)
		#_LINUX_FLAVOURS="486 686-pae"
		_LINUX_FLAVOURS="generic-pae"
		_SOURCE="true"
		;;
esac

[ -n $http_proxy ] && OPTS="--apt-http-proxy $http_proxy \"

lb config noauto \
	--clean \
	--distribution trusty \
	--ignore-system-defaults \
	--mode ubuntu \
	--archive-areas 'main restricted universe multiverse' \
	--debian-installer live \
	--linux-flavours "${_LINUX_FLAVOURS}" \
	--linux-packages "linux-image linux-headers" \
	--source "${_SOURCE}" \
        --iso-application XBMCbuntu \
        --iso-volume XBMCbuntu \
	--backports false \
        --iso-publisher http://xbmc.org \
	--mirror-bootstrap http://ubuntu.inode.at/ubuntu/ \
	--mirror-chroot-security http://ubuntu.inode.at/ubuntu/ \
	$OPTS \
"${@}"
